### ISSUE TITLE
BUG: OOM in ./join-rows

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/ncov-ingest#374]
### Current Behavior

```
    459 [batch] [2022-12-12T20:50:46+01:00] Traceback (most recent call last):
    460 [batch] [2022-12-12T20:50:46+01:00]   File "/nextstrain/build/./bin/join-rows", line 34, in <module>
    461 [batch] [2022-12-12T20:50:46+01:00]     main()
    462 [batch] [2022-12-12T20:50:46+01:00]   File "/nextstrain/build/./bin/join-rows", line 21, in main
    463 [batch] [2022-12-12T20:50:46+01:00]     left = pd.read_csv(args.first_file, sep='\t', low_memory=False, na_filter = False)
    464 [batch] [2022-12-12T20:50:46+01:00]   File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    465 [batch] [2022-12-12T20:50:46+01:00]     return func(*args, **kwargs)
    466 [batch] [2022-12-12T20:50:46+01:00]   File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    467 [batch] [2022-12-12T20:50:46+01:00]     return func(*args, **kwargs)
    468 [batch] [2022-12-12T20:50:46+01:00]   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read>
    469 [batch] [2022-12-12T20:50:46+01:00]     return _read(filepath_or_buffer, kwds)
    470 [batch] [2022-12-12T20:50:46+01:00]   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    471 [batch] [2022-12-12T20:50:46+01:00]     return parser.read(nrows)
    472 [batch] [2022-12-12T20:50:46+01:00]   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    473 [batch] [2022-12-12T20:50:46+01:00]     ) = self._engine.read(  # type: ignore[attr-defined]
    474 [batch] [2022-12-12T20:50:46+01:00]   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 235>
    475 [batch] [2022-12-12T20:50:46+01:00]     data = self._reader.read(nrows)
    476 [batch] [2022-12-12T20:50:46+01:00]   File "pandas/_libs/parsers.pyx", line 790, in pandas._libs.parsers.TextReader.read
    477 [batch] [2022-12-12T20:50:46+01:00]   File "pandas/_libs/parsers.pyx", line 883, in pandas._libs.parsers.TextReader._read_rows
    478 [batch] [2022-12-12T20:50:46+01:00]   File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
    479 [batch] [2022-12-12T20:50:46+01:00] pandas.errors.ParserError: Error tokenizing data. C error: out of memory
```

**Comment by joverlee521** [comment]
Resolved by https://github.com/nextstrain/ncov-ingest/pull/377
